---
version: "3.9"
services:
  mainnetwork:
    ports:
      - 3000:3000
      - 8000:8000
      - 5050:5050
      - 5555:5555
      - 8081:8081
      - 19000:19000
  pgadmin:
    network_mode: service:mainnetwork
    image: dpage/pgadmin4:9.7.0
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
  frontend:
    network_mode: service:mainnetwork
  backend:
    depends_on:
      - redis
    command: ["./dev.sh"]
    network_mode: service:mainnetwork
    volumes:
      - storage-data:/app/storage
  flower:
    depends_on:
      - redis
      - celery-worker
    network_mode: service:mainnetwork
    image: mher/flower
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
    command: >
      celery
        --broker=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
        flower
        --port=5555
        --basic_auth=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin123}
    restart: unless-stopped
  mobileapp:
    network_mode: service:mainnetwork
volumes:
  pg-admin-data:
  storage-data:
